#
#    ███╗░░░███╗██╗███╗░░██╗███████╗░██████╗████████╗░█████╗░██████╗░███████╗
#    ████╗░████║██║████╗░██║██╔════╝██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝
#    ██╔████╔██║██║██╔██╗██║█████╗░░╚█████╗░░░░██║░░░██║░░██║██████╔╝█████╗░░
#    ██║╚██╔╝██║██║██║╚████║██╔══╝░░░╚═══██╗░░░██║░░░██║░░██║██╔══██╗██╔══╝░░
#    ██║░╚═╝░██║██║██║░╚███║███████╗██████╔╝░░░██║░░░╚█████╔╝██║░░██║███████╗
#    ╚═╝░░░░░╚═╝╚═╝╚═╝░░╚══╝╚══════╝╚═════╝░░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝╚══════╝
# -------------------------------------------------------------------------------#
# Official MineStore Plugin by ChromMob                             -------#
# Version: 1.0                                            ---------#
#--------------------------------------------------------#
# Modes: websocket or web-listener.                     #
# Websocket requires opened port.                    #
# Web-listener listens to your URL.                 #
#------------------------------------------------#
mode: websocket
#------------------------------------------------#

#------------------------------------------------#
# Websocket port for plugin (port must be opened)
port: 33266
password: "hard_password_here"
#------------------------------------------------#

#------------------------------------------------#
# Web listener mode enter your secret-key below
secret-key: "hard_secret_key_here"
#------------------------------------------------#

#------------------------------------------------#
# Link to your store's API                       #
store-api: "https://yourstore.com/api/"
api-key: "hard_api_key_here"
#------------------------------------------------#